### PR TITLE
DRILL-7984: Support Clickhouse using JDBC Storage Plugin

### PR DESCRIPTION
**Pull request by Leon-WTF**

### CODE REVIEW

**Comment by Leon-WTF** [comment]
@vdiravka picked clickhouse and presto dialects, CALCITE-4614 for EXASOL depends on some others commits.

**Comment by vdiravka** [comment]
One more question: 
do you know why absence of `// End ClickHouseSqlDialect.java` in the original Calcite repo doesn't fail, but here is it's a required thing?

**Comment by vvysotskyi** [comment]
Perhaps initially it was a checkstyle rule that was removed in a newer version of Calcite.

**Comment by vdiravka** [comment]
I found that commit:
https://github.com/apache/calcite/commit/571731b80a58eb095ebac7123285c375e7afff90
So it can be revisited in scope of Calcite version update.

+1 LGTM

**Comment by Leon-WTF** [comment]
@vdiravka will you help to assign a reviewer for this PR? and you will help to upload the jar after this PR merged, right?

**Comment by vdiravka** [comment]
I don't have permissions to merge this PR. Are you able to merge and proceed according to: https://github.com/vvysotskyi/drill-calcite/wiki ? If no, please ask @vvysotskyi to merge it.

**Comment by vvysotskyi** [comment]
@vdiravka, please accept the invitation, so you will have all required permissions.

**Pull request merged**
